USE ECOMMERCE;

SHOW TABLES;

-- Produtos por clientes
SELECT * FROM CLIENTS;

SELECT CONCAT(CLIENTS.FNAME,' ', CLIENTS.LNAME) AS CLIENTE,
	   CLIENTS.ADDRESS AS ENDEREÇO,
       ORDERS.ORDERSTATUS AS STATUS,
       ORDERS.ORDERDESCRIPTION AS ORIGEM,
       PRODUCT.PNAME AS PRODUTO,
       SUM(PRODUCTORDER.POQUANTITY) AS TOTAL_ITEM
	   FROM CLIENTS
	  INNER JOIN ORDERS
		 ON CLIENTS.IDCLIENT
	  INNER JOIN PRODUCT 
		 ON IDPRODUCT
	  INNER JOIN PRODUCTORDER
		 ON IDPRODUCT
	  GROUP BY CLIENTE, ENDEREÇO, STATUS, ORIGEM, PRODUTO;
      
-- Relação de estoque e fornecedores
SELECT * FROM PRODUCTSTORAGE;

SELECT PRODUCTSTORAGE.STORAGELOCATION AS LOCAL,
	   PRODUCTSTORAGE.QUANTITY AS QUANTIDADE,
       PRODUCT.PNAME AS PRODUTO,
       CASE 
			WHEN productStorage.QUANTITY >= 200 THEN 'ESTOQUE OK'
            WHEN productStorage.QUANTITY BETWEEN 100 AND 199 THEN 'ATENÇÃO'
            WHEN productStorage.QUANTITY <= 99 THEN 'ESTOQUE BAIXO'
	    END AS 'CLASSIFICAÇÃO DE ESTOQUE',
       SUPPLIER.SOCIALNAME AS FORNECEDOR,
       SUPPLIER.CNPJ
       FROM PRODUCTSTORAGE
		 INNER JOIN SUPPLIER ON IDSUPPLIER
         INNER JOIN PRODUCT ON IDPRODUCT;
         
-- VENDAS POR VENDEDOR E AVALIAÇÃO.
SELECT * FROM PRODUCT;

SELECT SELLER.SOCIALNAME AS VENDEDOR,
	   SELLER.CNPJ,
       SELLER.CPF,
       SELLER.LOCATION AS LOCALIZAÇÃO,
       PRODUCT.PNAME AS PRODUTO, 
       PRODUCTSELLER.PRODQUANTITY AS 'QUANTIDADE VENDIDA',
       CASE 
			WHEN PRODUCT.avaliação = 5 THEN 'EXCELENTE'
            WHEN PRODUCT.avaliação = 4 THEN 'OTIMO'
            WHEN PRODUCT.avaliação = 3 THEN 'BOM'
            WHEN PRODUCT.avaliação = 2 THEN 'RUIM'
            WHEN PRODUCT.avaliação = 1 THEN 'PESSIMO'
	    END AS 'Classificação de Venda'
	   FROM SELLER
		INNER JOIN PRODUCTSELLER ON IDSELLER
        INNER JOIN PRODUCT ON IDPRODUCT;

		


        
